<?php

declare(strict_types=1);

namespace Scraper\ScraperChronopost;

/**
 * Class which returns the class map definition.
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS.
     *
     * @return array<string>
     */
    final public static function get(): array
    {
        return [
            'esdResultContraintesAgenceValue' => '\Scraper\ScraperChronopost\StructType\EsdResultContraintesAgenceValue',
            'esdContraintesAgence' => '\Scraper\ScraperChronopost\StructType\EsdContraintesAgence',
            'resultGetReservedSkybillValue' => '\Scraper\ScraperChronopost\StructType\ResultGetReservedSkybillValue',
            'resultReservationExpeditionValue' => '\Scraper\ScraperChronopost\StructType\ResultReservationExpeditionValue',
            'esdValue' => '\Scraper\ScraperChronopost\StructType\EsdValue',
            'headerValue' => '\Scraper\ScraperChronopost\StructType\HeaderValue',
            'shipperValue' => '\Scraper\ScraperChronopost\StructType\ShipperValue',
            'customerValue' => '\Scraper\ScraperChronopost\StructType\CustomerValue',
            'recipientValue' => '\Scraper\ScraperChronopost\StructType\RecipientValue',
            'refValue' => '\Scraper\ScraperChronopost\StructType\RefValue',
            'skybillValue' => '\Scraper\ScraperChronopost\StructType\SkybillValue',
            'skybillParamsValue' => '\Scraper\ScraperChronopost\StructType\SkybillParamsValue',
            'scheduledValue' => '\Scraper\ScraperChronopost\StructType\ScheduledValue',
            'appointmentValue' => '\Scraper\ScraperChronopost\StructType\AppointmentValue',
            'resultExpeditionValue' => '\Scraper\ScraperChronopost\StructType\ResultExpeditionValue',
            'esdWithRefClientValue' => '\Scraper\ScraperChronopost\StructType\EsdWithRefClientValue',
            'esdValue3' => '\Scraper\ScraperChronopost\StructType\EsdValue3',
            'headerValueV2' => '\Scraper\ScraperChronopost\StructType\HeaderValueV2',
            'shipperValueV2' => '\Scraper\ScraperChronopost\StructType\ShipperValueV2',
            'recipientValueV2' => '\Scraper\ScraperChronopost\StructType\RecipientValueV2',
            'refValueV2' => '\Scraper\ScraperChronopost\StructType\RefValueV2',
            'skybillWithDimensionsValue' => '\Scraper\ScraperChronopost\StructType\SkybillWithDimensionsValue',
            'skybillWithDimensionsValueV2' => '\Scraper\ScraperChronopost\StructType\SkybillWithDimensionsValueV2',
            'skybillWithDimensionsValueV3' => '\Scraper\ScraperChronopost\StructType\SkybillWithDimensionsValueV3',
            'skybillWithDimensionsValueV4' => '\Scraper\ScraperChronopost\StructType\SkybillWithDimensionsValueV4',
            'skybillWithDimensionsValueV5' => '\Scraper\ScraperChronopost\StructType\SkybillWithDimensionsValueV5',
            'skybillWithDimensionsValueV6' => '\Scraper\ScraperChronopost\StructType\SkybillWithDimensionsValueV6',
            'skybillWithDimensionsValueV7' => '\Scraper\ScraperChronopost\StructType\SkybillWithDimensionsValueV7',
            'skybillWithDimensionsValueV8' => '\Scraper\ScraperChronopost\StructType\SkybillWithDimensionsValueV8',
            'skybillParamsValueV2' => '\Scraper\ScraperChronopost\StructType\SkybillParamsValueV2',
            'recipientLocalValue' => '\Scraper\ScraperChronopost\StructType\RecipientLocalValue',
            'recipientLocalValueV2' => '\Scraper\ScraperChronopost\StructType\RecipientLocalValueV2',
            'customsValue' => '\Scraper\ScraperChronopost\StructType\CustomsValue',
            'articleValue' => '\Scraper\ScraperChronopost\StructType\ArticleValue',
            'resultShippingValue' => '\Scraper\ScraperChronopost\StructType\ResultShippingValue',
            'resultMultiParcelExpeditionValue' => '\Scraper\ScraperChronopost\StructType\ResultMultiParcelExpeditionValue',
            'resultMultiParcelValue' => '\Scraper\ScraperChronopost\StructType\ResultMultiParcelValue',
            'esdWithRefClientValueV2' => '\Scraper\ScraperChronopost\StructType\EsdWithRefClientValueV2',
            'resultExpeditionValueV3' => '\Scraper\ScraperChronopost\StructType\ResultExpeditionValueV3',
            'resultMonoParcelExpeditionValue' => '\Scraper\ScraperChronopost\StructType\ResultMonoParcelExpeditionValue',
            'resultGetRouting' => '\Scraper\ScraperChronopost\StructType\ResultGetRouting',
            'geopostResultDto' => '\Scraper\ScraperChronopost\StructType\GeopostResultDto',
            'skybillValueV2' => '\Scraper\ScraperChronopost\StructType\SkybillValueV2',
            'resultFaisabiliteESD' => '\Scraper\ScraperChronopost\StructType\ResultFaisabiliteESD',
            'donneurDOrdre' => '\Scraper\ScraperChronopost\StructType\DonneurDOrdre',
            'adresseEnlevement' => '\Scraper\ScraperChronopost\StructType\AdresseEnlevement',
            'adresseEnlevementV2' => '\Scraper\ScraperChronopost\StructType\AdresseEnlevementV2',
            'adresseEnlevementV3' => '\Scraper\ScraperChronopost\StructType\AdresseEnlevementV3',
            'particularitesEsd' => '\Scraper\ScraperChronopost\StructType\ParticularitesEsd',
            'options' => '\Scraper\ScraperChronopost\StructType\Options',
            'resultEnlevementNational' => '\Scraper\ScraperChronopost\StructType\ResultEnlevementNational',
            'infoEnlevement' => '\Scraper\ScraperChronopost\StructType\InfoEnlevement',
            'resultAnnulerEnlevementV2' => '\Scraper\ScraperChronopost\StructType\ResultAnnulerEnlevementV2',
            'esdCancelStatutValue' => '\Scraper\ScraperChronopost\StructType\EsdCancelStatutValue',
            'resultGetReservedSkybillWithTypeValue' => '\Scraper\ScraperChronopost\StructType\ResultGetReservedSkybillWithTypeValue',
            'destinatairesDpd' => '\Scraper\ScraperChronopost\StructType\DestinatairesDpd',
            'destinataireDpd' => '\Scraper\ScraperChronopost\StructType\DestinataireDpd',
            'adresseDestinataire' => '\Scraper\ScraperChronopost\StructType\AdresseDestinataire',
            'infoClient' => '\Scraper\ScraperChronopost\StructType\InfoClient',
            'particularites' => '\Scraper\ScraperChronopost\StructType\Particularites',
            'particularitesColisDpd' => '\Scraper\ScraperChronopost\StructType\ParticularitesColisDpd',
            'infoDouanieres' => '\Scraper\ScraperChronopost\StructType\InfoDouanieres',
            'resultPickupOrCollectionRequest' => '\Scraper\ScraperChronopost\StructType\ResultPickupOrCollectionRequest',
            'resultReservationMultiParcelExpeditionValue' => '\Scraper\ScraperChronopost\StructType\ResultReservationMultiParcelExpeditionValue',
            'resultParcelValue' => '\Scraper\ScraperChronopost\StructType\ResultParcelValue',
            'resultReservationMultiParcelExpeditionValueV2' => '\Scraper\ScraperChronopost\StructType\ResultReservationMultiParcelExpeditionValueV2',
            'resultAnnulerEnlevement' => '\Scraper\ScraperChronopost\StructType\ResultAnnulerEnlevement',
            'statut' => '\Scraper\ScraperChronopost\StructType\Statut',
            'entry' => '\Scraper\ScraperChronopost\StructType\Entry',
            'resultReservationExpeditionValueV2' => '\Scraper\ScraperChronopost\StructType\ResultReservationExpeditionValueV2',
            'skybillValueBase' => '\Scraper\ScraperChronopost\StructType\SkybillValueBase',
            'resultShippingInfo' => '\Scraper\ScraperChronopost\StructType\ResultShippingInfo',
            'error' => '\Scraper\ScraperChronopost\StructType\Error',
            'detail' => '\Scraper\ScraperChronopost\StructType\Detail',
            'shippingInfo' => '\Scraper\ScraperChronopost\StructType\ShippingInfo',
            'rechercherContraintesEnlevementV2' => '\Scraper\ScraperChronopost\StructType\RechercherContraintesEnlevementV2',
            'rechercherContraintesEnlevementV2Response' => '\Scraper\ScraperChronopost\StructType\RechercherContraintesEnlevementV2Response',
            'getReservedSkybill' => '\Scraper\ScraperChronopost\StructType\GetReservedSkybill',
            'getReservedSkybillResponse' => '\Scraper\ScraperChronopost\StructType\GetReservedSkybillResponse',
            'shippingWithReservationAndESDWithRefClientPC' => '\Scraper\ScraperChronopost\StructType\ShippingWithReservationAndESDWithRefClientPC',
            'shippingWithReservationAndESDWithRefClientPCResponse' => '\Scraper\ScraperChronopost\StructType\ShippingWithReservationAndESDWithRefClientPCResponse',
            'shippingV3' => '\Scraper\ScraperChronopost\StructType\ShippingV3',
            'shippingV3Response' => '\Scraper\ScraperChronopost\StructType\ShippingV3Response',
            'shippingV2' => '\Scraper\ScraperChronopost\StructType\ShippingV2',
            'shippingV2Response' => '\Scraper\ScraperChronopost\StructType\ShippingV2Response',
            'shippingMultiParcelV7' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelV7',
            'shippingMultiParcelV7Response' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelV7Response',
            'shippingWithESDOnlyV2' => '\Scraper\ScraperChronopost\StructType\ShippingWithESDOnlyV2',
            'shippingWithESDOnlyV2Response' => '\Scraper\ScraperChronopost\StructType\ShippingWithESDOnlyV2Response',
            'shippingMultiParcelV6' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelV6',
            'shippingMultiParcelV6Response' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelV6Response',
            'shippingMultiParcelV5' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelV5',
            'shippingMultiParcelV5Response' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelV5Response',
            'shippingV7' => '\Scraper\ScraperChronopost\StructType\ShippingV7',
            'shippingV7Response' => '\Scraper\ScraperChronopost\StructType\ShippingV7Response',
            'getRouting' => '\Scraper\ScraperChronopost\StructType\GetRouting',
            'getRoutingResponse' => '\Scraper\ScraperChronopost\StructType\GetRoutingResponse',
            'shippingMultiParcelV4' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelV4',
            'shippingMultiParcelV4Response' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelV4Response',
            'shippingV6' => '\Scraper\ScraperChronopost\StructType\ShippingV6',
            'shippingV6Response' => '\Scraper\ScraperChronopost\StructType\ShippingV6Response',
            'shippingMultiParcelV3' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelV3',
            'shippingMultiParcelV3Response' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelV3Response',
            'shippingV5' => '\Scraper\ScraperChronopost\StructType\ShippingV5',
            'shippingV5Response' => '\Scraper\ScraperChronopost\StructType\ShippingV5Response',
            'shippingMultiParcelV2' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelV2',
            'shippingMultiParcelV2Response' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelV2Response',
            'shippingV4' => '\Scraper\ScraperChronopost\StructType\ShippingV4',
            'shippingV4Response' => '\Scraper\ScraperChronopost\StructType\ShippingV4Response',
            'faisabiliteESD' => '\Scraper\ScraperChronopost\StructType\FaisabiliteESD',
            'faisabiliteESDResponse' => '\Scraper\ScraperChronopost\StructType\FaisabiliteESDResponse',
            'creerEnlevementNational' => '\Scraper\ScraperChronopost\StructType\CreerEnlevementNational',
            'creerEnlevementNationalResponse' => '\Scraper\ScraperChronopost\StructType\CreerEnlevementNationalResponse',
            'shippingWithESDOnly' => '\Scraper\ScraperChronopost\StructType\ShippingWithESDOnly',
            'shippingWithESDOnlyResponse' => '\Scraper\ScraperChronopost\StructType\ShippingWithESDOnlyResponse',
            'annulerEnlevementsV2' => '\Scraper\ScraperChronopost\StructType\AnnulerEnlevementsV2',
            'annulerEnlevementsV2Response' => '\Scraper\ScraperChronopost\StructType\AnnulerEnlevementsV2Response',
            'getReservedSkybillWithTypeAndModeByReservation' => '\Scraper\ScraperChronopost\StructType\GetReservedSkybillWithTypeAndModeByReservation',
            'getReservedSkybillWithTypeAndModeByReservationResponse' => '\Scraper\ScraperChronopost\StructType\GetReservedSkybillWithTypeAndModeByReservationResponse',
            'creerEnlevementEurope' => '\Scraper\ScraperChronopost\StructType\CreerEnlevementEurope',
            'creerEnlevementEuropeResponse' => '\Scraper\ScraperChronopost\StructType\CreerEnlevementEuropeResponse',
            'shippingMultiParcelWithReservation' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelWithReservation',
            'shippingMultiParcelWithReservationResponse' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelWithReservationResponse',
            'rechercherContraintesEnlevement' => '\Scraper\ScraperChronopost\StructType\RechercherContraintesEnlevement',
            'rechercherContraintesEnlevementResponse' => '\Scraper\ScraperChronopost\StructType\RechercherContraintesEnlevementResponse',
            'shippingWithReservationAndESDWithRefClient' => '\Scraper\ScraperChronopost\StructType\ShippingWithReservationAndESDWithRefClient',
            'shippingWithReservationAndESDWithRefClientResponse' => '\Scraper\ScraperChronopost\StructType\ShippingWithReservationAndESDWithRefClientResponse',
            'shippingMultiParcel' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcel',
            'shippingMultiParcelResponse' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelResponse',
            'getSkybill' => '\Scraper\ScraperChronopost\StructType\GetSkybill',
            'getSkybillResponse' => '\Scraper\ScraperChronopost\StructType\GetSkybillResponse',
            'getReservedSkybillWithTypeAndModeAuth' => '\Scraper\ScraperChronopost\StructType\GetReservedSkybillWithTypeAndModeAuth',
            'getReservedSkybillWithTypeAndModeAuthResponse' => '\Scraper\ScraperChronopost\StructType\GetReservedSkybillWithTypeAndModeAuthResponse',
            'shipping' => '\Scraper\ScraperChronopost\StructType\Shipping',
            'shippingResponse' => '\Scraper\ScraperChronopost\StructType\ShippingResponse',
            'getReservedSkybillWithTypeAndMode' => '\Scraper\ScraperChronopost\StructType\GetReservedSkybillWithTypeAndMode',
            'getReservedSkybillWithTypeAndModeResponse' => '\Scraper\ScraperChronopost\StructType\GetReservedSkybillWithTypeAndModeResponse',
            'getReservedSkybillWithType' => '\Scraper\ScraperChronopost\StructType\GetReservedSkybillWithType',
            'getReservedSkybillWithTypeResponse' => '\Scraper\ScraperChronopost\StructType\GetReservedSkybillWithTypeResponse',
            'shippingMultiParcelWithReservationV3' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelWithReservationV3',
            'shippingMultiParcelWithReservationV3Response' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelWithReservationV3Response',
            'annulerEnlevements' => '\Scraper\ScraperChronopost\StructType\AnnulerEnlevements',
            'annulerEnlevementsResponse' => '\Scraper\ScraperChronopost\StructType\AnnulerEnlevementsResponse',
            'shippingMultiParcelWithReservationV2' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelWithReservationV2',
            'shippingMultiParcelWithReservationV2Response' => '\Scraper\ScraperChronopost\StructType\ShippingMultiParcelWithReservationV2Response',
            'shippingWithReservationV2' => '\Scraper\ScraperChronopost\StructType\ShippingWithReservationV2',
            'shippingWithReservationV2Response' => '\Scraper\ScraperChronopost\StructType\ShippingWithReservationV2Response',
            'getShippingInformation' => '\Scraper\ScraperChronopost\StructType\GetShippingInformation',
            'getShippingInformationResponse' => '\Scraper\ScraperChronopost\StructType\GetShippingInformationResponse',
            'shippingWithReservation' => '\Scraper\ScraperChronopost\StructType\ShippingWithReservation',
            'shippingWithReservationResponse' => '\Scraper\ScraperChronopost\StructType\ShippingWithReservationResponse',
        ];
    }
}
